# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 645af874fcbacecd12a188eb9391e71e8028e92cd660a29cf1dcda9d5af6305f9349d9e4f94f1286502b057bef8c1471b11f52bfd997eee0be633a2dddfe76a2

test:
  secret_key_base: a948c56385251942d5f65baef3f7ff19da8724adf9924741f49d31ed8bf371016e0e409a13544688fa698419ecfd800d15be45be0fc74a7aa99d49fa208d7416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
